name: plink
version: 0.1.0
author: Axel Christ <adracus@gmail.com>
description: Plink is an orm which focuses on easy to use implementation.
homepage: https://github.com/Adracus/plink
documentation: https://github.com/Adracus/plink
dependencies:
  logging: '>=0.9.2 <0.10.0'
  mock: ">=0.11.0+2 <0.12.0"
  postgresql: '>=0.2.14 <0.3.0'
  u_til: '>=0.1.0 <0.2.0'
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
